### ISSUE TITLE
Dependencies and gitignore

### ISSUE THREAD

**Issue by shivupa** [Cavenfish/autogamess#8]
These are both minor and easy to address, but I think they would help contributors/users.
# gitignore
If you install from source (e.g. ` python -m pip install -e . --user` as someone might do if they are doing development work, files and directories are created that aren't ignored by git like `autogamess.egg-info/`. These could be accidentally committed if someone isn't careful adding a gitignore helps. You can add this [one for  python](https://github.com/github/gitignore/blob/master/Python.gitignore).

# requirements
The list of requirements is nice, but creating a requirements.txt is easier.
Creating a file `requirements.txt` could change the process to:
```
python -m pip install -r requirements.txt --user
python -m pip install -e . --user
```
if installing from source.
The `requirements.txt` only needs to have this in it:
```
NumPy
SciPy
Pandas
basis_set_exchange
PeriodicElements
openpyxl
```

**Comment by Cavenfish** [comment]
Hey @shivupa  in terms of the `requirements.txt` if this is just for automate install of dependencies when pip installing, i think it is not necessary since i have already configured the `setup.py`  to automatically install dependencies when pip installing. I will still add the `.txt` file to the repository though.
